//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvMan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortization
    {
        public string Name_ID { get; set; }
        public string Ticker { get; set; }
        public string Period { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
