//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvMan2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvestDB2Entities : DbContext
    {
        public InvestDB2Entities()
            : base("name=InvestDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amortization> Amortizations { get; set; }
        public virtual DbSet<BalanceCapital> BalanceCapitals { get; set; }
        public virtual DbSet<CurrentAsset> CurrentAssets { get; set; }
        public virtual DbSet<CurrentLiability> CurrentLiabilities { get; set; }
        public virtual DbSet<Ebit> Ebits { get; set; }
        public virtual DbSet<TotalAsset> TotalAssets { get; set; }
        public virtual DbSet<StocksDetail> StocksDetails { get; set; }
        public virtual DbSet<StocksQuote> StocksQuotes { get; set; }
    }
}
