//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvMan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksQuote
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Ticker { get; set; }
        public string Name_ID { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<decimal> QuoteValue { get; set; }
    }
}
